title: Savage Wars Hammer Worlds

collections:
  crew:
    output: true
  rules:

defaults:
  - scope:
      path: ""
      type: crew
    values:
      layout: person

sass:
  style: compressed

base_path: ""
url: "https://swade-wh40k.github.io"

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

kramdown:
  auto_ids: false
  auto_id_prefix: false
  auto_id_stripping: false

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json
